# Generated by Django 5.2.15 on 2026-07-03 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeriesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "series",
                "db_table": "series",
            },
        ),
        migrations.CreateModel(
            name="TagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(unique=True)),
            ],
            options={
                "db_table": "tag",
            },
        ),
        migrations.CreateModel(
            name="ArticleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "locale",
                    models.CharField(
                        choices=[("fr", "fr"), ("en", "en")], default="fr", max_length=2
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("standard", "standard"),
                            ("code_3d", "code_3d"),
                            ("til", "til"),
                        ],
                        default="standard",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("excerpt", models.TextField(blank=True)),
                ("body_mdx", models.TextField()),
                ("scene", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("published", "published"),
                            ("archived", "archived"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("reading_time", models.PositiveIntegerField(default=1)),
                ("series_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "translation_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translations",
                        to="publishing.articlemodel",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="publishing.seriesmodel",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="publishing.tagmodel"
                    ),
                ),
            ],
            options={
                "db_table": "article",
                "ordering": ["-published_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "locale"), name="uniq_slug_locale"
                    )
                ],
            },
        ),
    ]
